- name: Install Cinder Packages (Ubuntu)
  apt:
    name:
      - cinder-api
      - cinder-scheduler
    state: latest

- name: Update Database Connection
  replace:
    dest: /etc/cinder/cinder.conf
    regexp: connection = mysql+pymysql://cinder:CINDER_DBPASS@controller/cinder
    replace: connection = mysql+pymysql://cinder:admin123@controller/cinder
    backup: yes

- name: Update RabbitMQ Transport
  replace:
    dest: /etc/cinder/cinder.conf
    regexp: transport_url = rabbit://openstack:RABBIT_PASS@controller
    replace: transport_url = rabbit://openstack:admin123@controller
    backup: yes

- name: Update Keystone Authentication
  lineinfile:
    dest: /etc/cinder/cinder.conf
    line: 'auth_strategy = keystone'
    state: present
    backup: yes

- name: Update Keystone Auth Token
  lineinfile:
    dest: /etc/cinder/cinder.conf
    insertafter: '\[keystone_authtoken\]'
    line: '{{ item }}'
    state: present
    backup: yes
  with_items:
    - www_authenticate_uri = http://controller:5000
    - auth_url = http://controller:5000
    - memcached_servers = controller:11211
    - auth_type = password
    - project_domain_name = default
    - user_domain_name = default
    - project_name = service
    - username = cinder
    - password = pass123

- name: Update IP Address
  lineinfile:
    dest: /etc/cinder/cinder.conf
    line: 'my_ip = 192.168.52.103'
    state: present
    backup: yes

- name: Update Lock Path
  lineinfile:
    dest: /etc/cinder/cinder.conf
    line: 'lock_path = /var/lib/cinder/tmp'
    state: present
    backup: yes

- name: Populate the Cinder Database
  shell: |
    cinder-manage db sync

- name: Update Nova Configuration - Region Name
  lineinfile:
    dest: /etc/nova/nova.conf
    line: 'os_region_name = RegionOne'
    state: present
    backup: yes
